language: python

python:
  - "3.4"
  - "3.5"

sudo: required 

# command to install dependencies
install:
    - sudo apt-get install npm
    - npm install bower
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - pip install --upgrade pytest
    - pip install django-bower    
# command to run tests
script:
    - cd src
    - python manage.py bower_install 
    - py.test -runxfail
