language: python

python:
  - "3.4"

sudo: required 

# command to install dependencies
install:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - pip install --upgrade pytest
    - pip install django-bower    

before_script:
    - npm install -g bower
    
# command to run tests
script:
    - mkdir -p bower
	- tar -zxvf bower_components.tar.gz -C bower/
    - mkdir -p collect/static
    - cd src
    - python manage.py collectstatic --noinput 
    - py.test -runxfail
