language: python

python:
  - "3.4"
  - "3.5"

sudo: required 

# command to install dependencies
install:
    - sudo apt-get install npm
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - pip install --upgrade pytest
    - pip install django-bower    

before_script:
    - npm install -g bower
    
# command to run tests
script:
    - mkdir -p bower/bower_components
    - mkdir -p collect/static
    - cd src
    - [ -d codeschool/static/bower_components ] || mkdir -p codeschool/static/bower_components
    - python manage.py bower_install
    - python manage.py collectstatic --noinput 
    - py.test -runxfail
