language: python

python:
  - "3.4"

# command to install dependencies
install:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - pip install git+https://github.com/joke2k/faker 
    - pip install lazy 
    - pip install bs4
    - pip install decorator
    - pip install django-debug-toolbar
    - pip install django-userena
    - pip install django-viewpack
    - pip install djangorestframework
    - pip install djinga
    - pip install easy-thumbnails
    - pip install frozendict
    - pip install generic
    - pip install html2text
    - pip install html5lib
    - pip install ipython
    - pip install ipython-genutils
    - pip install Jinja2
    - pip install jinja2-django-tags
    - pip install judge
    - pip install Markdown
    - pip install MarkupSafe
    - pip install node
    - pip install numpy
    - pip install odict
    - pip install pandas
    - pip install pexpect
    - pip install pickleshare
    - pip install Pillow
    - pip install plumber
    - pip install ply
    - pip install psutil
    - pip install ptyprocess
    - pip install py
    - pip install pygeneric
    - pip install pytest
    - pip install python-dateutil
    - pip install pytuga
    - pip install pytz
    - pip install rcssmin
    - pip install rjsmin
    - pip install simplegeneric
    - pip install six
    - pip install slimit
    - pip install sqlparse
    - pip install traitlets
    - pip install Unidecode
    - pip install wagtail
    - pip install Willow
    - pip install zope.component
    - pip install zope.deprecation
    - pip install zope.event
    - pip install zope.interface
    - pip install zope.lifecycleevent
    - pip install ejudge
# command to run tests
script: 
    - python src/manage.py test
