language: python

python:
  - "3.4"
  - "3.5"

sudo: required 

# command to install dependencies
install:
    - sudo apt-get install npm
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install --upgrade pytest
    - pip install django-bower    

before_script:
    - npm install -g bower
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5
    
# command to run tests
script:
    - mkdir -p bower
    - tar -zxvf bower_components.tar.gz -C bower/
    - mkdir -p collect/static
    - mkdir -p src/codeschool/bower/
    - tar -zxvf bower_components.tar.gz -C src/codeschool/bower/
    - cd src
    - rm cs_*/migrations/0*
    - python manage.py makemigrations
    - python manage.py harvest -v 3 --keepdb cs_auth/features/
