# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_sessions_as_helper', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_sessions_as_owner', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.CodingIoResponse')),
            ],
        ),
        migrations.CreateModel(
            name='LineComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commment', models.TextField()),
                ('help_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_line', to='cs_friendhelp.HelpSession')),
            ],
        ),
    ]
